config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    passwords: 'users/passwords'
  }

  resources :events do
    member do
      get :followup
      post :join
    end
  end

  root to: "events#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  validates :name, presence: true
  validates :lat, presence: true
  validates :lon, presence: true
  validates :location_name, presence: true
  validates :description, presence: true
  validates :starts_at, presence: true

  scope :upcoming, ->{ where("starts_at >= ?", Time.now).order("starts_at ASC") }

  has_many :user_events, dependent: :destroy
  has_many :users, through: :user_events

  def city_name
    location_name.match(/\w+,? (?=AL|AK|AS|AZ|AR|CA|CO|CT|DE|DC|FM|FL|GA|GU|HI|ID|IL|IN|IA|KS|KY|LA|ME|MH|MD|MA|MI|MN|MS|MO|MT|NE|NV|NH|NJ|NM|NY|NC|ND|MP|OH|OK|OR|PW|PA|PR|RI|SC|SD|TN|TX|UT|VT|VI|VA|WA|WV|WI|WY)[A-Z]{2}/)[0]
  end

  def related_events
    if name.downcase.include? "women"
      Event.where("name ILIKE '%women%' OR name ILIKE '%woman%'").where.not(id: id)
    else
      Event.where("name NOT ILIKE '%women%' AND name NOT ILIKE '%woman%'").where.not(id: id)
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :user_events, dependent: :destroy
  has_many :events, through: :user_events

  before_validation :clean_phone, if: :phone_changed?
  before_validation :set_password, on: :create
  validates :phone, presence: true, format: {with: /\d{10,11}/, message: "must be 10 or 11 digits."}, if: :phone_required?


  def email_required?
    phone.blank?
  end

  def phone_required?
    email.blank?
  end

  # for form rendering
  def email_or_phone
    email.presence || phone.presence
  end

  # for form submission
  def email_or_phone=(val)
    if val.include?("@")
      self.email = val
    else
      self.phone = val
    end
  end

  private

  def clean_phone
    phone.gsub!(/\D/, '')
  end

  def set_password
    if password.blank?
      self.password = SecureRandom.hex(16)
    end
  end
end

app/models/user_event.rb
class UserEvent < ActiveRecord::Base
  belongs_to :user
  belongs_to :event

  after_commit :send_followup_email, on: :create

  def send_followup_email
    msg = EventMailer.followup(event, user)
    if msg.respond_to? :deliver_now
      msg.deliver_now
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def index
    @events = Event.upcoming.limit(20)

    respond_to do |format|
      format.html { render layout: "hero" }
      format.json
    end
  end

  def show
    @event = Event.find params[:id]
    @user = User.new
  end

  def followup
    @event = Event.find params[:id]
  end

  def join
    @event = Event.find params[:id]
    current_user.events << @event

    flash[:notice] = "Great! You're all set to receive updates about this event."
    redirect_to event_path(@event)
  end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  after_filter :confirm_user, only: :update
  private

  def confirm_user
    if resource.errors.empty?
      resource.confirm! unless resource.confirmed?
    end
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_permitted_parameters, only: :create

  # TODO: make create be event reg or create

  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) do |user_params|
      user_params.permit(:email, :phone, :email_or_phone, :password, :password_confirmation, event_ids: [])
    end
  end

  def after_sign_up_path_for(user)
    if params.fetch(:user, {})[:event_ids].present?
      flash[:notice] = "Great! You're all set to receive updates about this event."
      event_path(params[:user][:event_ids].first)
    else
      flash[:notice] = "Great! You're all set."
      root_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/events/followup.html.haml
.row.collapse
  .columns.small-12.event-details
    = link_to root_path, class: "logo-absolute" do
      = image_tag "logo-small.svg", class: "logo-absolute"
    .img= link_to image_tag(@event.image_url), event_path(@event)
    .info
      .title= link_to @event.name, event_path(@event)

.row
  .columns.small-12
    %p= simple_format @event.followup_description

.row
  .columns.small-12.text-center.margin-bottom-3
    = link_to "Call Your Legislator", image_url("hello_gov_demo.png"), class: "button success large color-white", target: "_blank"

.row
  .columns.small-12.related-actions
    %h4 Related Actions

    .row
      .columns.small-12
        - @event.related_events.each do |event|
          .row.collapse
            .columns.small-12.event-row
              .img= link_to image_tag(event.image_url), event_path(event)
              .info
                .title= link_to event.name, event_path(event)
                .row
                  .columns.small-6
                    = l event.starts_at.in_time_zone(event.timezone), format: :long
                  .columns.small-6.text-right
                    = icon "map-marker", class: "margin-right-1"
                    = event.city_name

.row
  .columns.small-12.margin-bottom-3
    .row
      .columns.small-4.text-center
        = link_to "https://www.facebook.com/sharer/sharer.php?#{ {u: root_url}.to_param }", target: "_blank" do
          = image_tag "facebook.svg", class: "icon"
      .columns.small-4.text-center
        = link_to "https://twitter.com/home?#{ {status: "I participated in #{@event.name}. Find your own way to make a difference! #{root_url} @findthefightorg"}.to_param}", target: "_blank" do
          = image_tag "twitter.svg", class: "icon"
      .columns.small-4.text-center
        = link_to "https://plus.google.com/share?#{ {url: root_url}.to_param }", target: "_blank" do
          = image_tag "google_plus.svg", class: "icon"

app/views/events/index.html.haml
.row
  .columns.small-12
    = form_for "search" do |f|
      .input-group
        = f.text_field "Location", class: "input-group-field"
        .input-group-button
          = f.submit "Search", class: "button success color-white"

.row
  .columns.small-12
    - @events.each do |event|
      .row.collapse
        .columns.small-12.event-row
          .img= link_to image_tag(event.image_url), event_path(event)
          .info
            .title= link_to event.name, event_path(event)
            .row
              .columns.small-6
                = l event.starts_at.in_time_zone(event.timezone), format: :long
              .columns.small-6.text-right
                = icon "map-marker", class: "margin-right-1"
                = event.city_name

app/views/events/show.html.haml
.row.collapse
  .columns.small-12.event-details
    = link_to root_path, class: "logo-absolute" do
      = image_tag "logo-small.svg", class: "logo-absolute"
    .img= link_to image_tag(@event.image_url), event_path(@event)
    .info
      .title= link_to @event.name, event_path(@event)
      .row
        .columns.small-12.medium-6
          = l @event.starts_at.in_time_zone(@event.timezone), format: :long
        .columns.small-12.medium-6.small-text-right
          = icon "map-marker", class: "margin-right-1"
          = @event.city_name

.row
  .columns.small-12
    %p= simple_format @event.description

.row
  .columns.small-12
    - if user_signed_in?
      - if current_user.event_ids.include? @event.id
        .callout.primary
          %p.lead You're going! Now tell your friends to join you!
          .row
            .columns.small-4.text-center
              = link_to "Share on Facebook", "https://www.facebook.com/sharer/sharer.php?#{ {u: request.original_url}.to_param }", target: "_blank"
            .columns.small-4.text-center
              = link_to "Share on Twitter", "https://twitter.com/home?#{ {status: "Join me at #{@event.name} #{event_url(@event)} @findthefightorg"}.to_param}", target: "_blank"
            .columns.small-4.text-center
              = link_to "Share on Google+", "https://plus.google.com/share?#{ {url: event_url(@event)}.to_param }", target: "_blank"
      - else
        = button_to "Join the Fight!", join_event_path(@event), method: :post, class: "button large full-width color-white", data: {disable_with: "Joining..."}
    - else
      = form_for @user, url: user_registration_path do |f|
        = f.text_field :email_or_phone, placeholder: "Email or phone number"
        = f.hidden_field :event_ids, value: @event.id, multiple: true
        = f.submit "Join the Fight!", class: "button large full-width success color-white", data: {disable_with: "Joining..."}

.row
  .columns.small-12
    #map{style: "min-height: 30vh", data: {lat: @event.lat, lon: @event.lon}}

app/views/layouts/application.html.haml
!!!
%html{:lang => "en"}
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %meta{:charset => "utf-8"}/
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}/
    %title= content_for?(:title) ? yield(:title) : "Find the Fight"
    = stylesheet_link_tag    "application"
    = javascript_include_tag "application", 'data-turbolinks-track' => true
    = javascript_include_tag "https://maps.googleapis.com/maps/api/js?key=AIzaSyCKCin-26T6INKx4awqFqrj1sfDPm3_92E&callback=setMapsReady", async: true, defer: true
    = csrf_meta_tags
  %body
    -# flash notifications
    - alert_mappings = {"info" => "primary", "notice" => "primary", "error" => "alert", "alert" => "alert"}
    - flash.each do |k, v|
      - next unless alert_mappings[k].present?
      .callout{class: [alert_mappings[k], k], data: {closable: true}}
        = v
        %button.close-button(aria-label="Dismiss alert" type="button" data-close)
          %span(aria-hidden="true") &times;
    = yield

app/views/layouts/hero.html.haml
!!!
%html{:lang => "en"}
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %meta{:charset => "utf-8"}/
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}/
    %title= content_for?(:title) ? yield(:title) : "Find the Fight"
    = stylesheet_link_tag    "application"
    = javascript_include_tag "application", 'data-turbolinks-track' => true
    = javascript_include_tag "https://maps.googleapis.com/maps/api/js?key=AIzaSyCKCin-26T6INKx4awqFqrj1sfDPm3_92E&callback=setMapsReady", async: true, defer: true
    = csrf_meta_tags
  %body
    .row.header-wrapper.margin-bottom-2
      .header-overlay
        = image_tag "logo-big.svg"
        %p Make a real change. Join the resistance.
    -# flash notifications
    - alert_mappings = {"info" => "primary", "notice" => "primary", "error" => "alert", "alert" => "alert"}
    - flash.each do |k, v|
      - next unless alert_mappings[k].present?
      .callout{class: [alert_mappings[k], k], data: {closable: true}}
        = v
        %button.close-button(aria-label="Dismiss alert" type="button" data-close)
          %span(aria-hidden="true") &times;
    = yield